### ISSUE TITLE
Can we edit source(src) at the image popover?

### ISSUE THREAD

**Issue by yumewang** [StudioJunkyard/summernote-image-attributes#14]
Can support input source directly, also upload from locally.

Before finding this, I have just finished a plugin which is just do this. I think maybe there also can support, that will be good.

If this is not a good idea, please just tell me. Thank you.
![3](https://cloud.githubusercontent.com/assets/2267888/20337758/05488c2e-ac0e-11e6-9355-d0fc9110ee6c.png)

And then, there has one issue about Chinese (Traditional) Translation. There should be as below:
`tooltipShapeOptions: ['響應式', '圓角', '圓形', '縮圖', '無' ],`
instead of 
`tooltipShapeOptions: ['圓角', '圓形', '縮圖', '無' ],`
Translation is just not enough.

ps: I am Chinese, not Chinese Taiwanese, so maybe '響應式' is not good word. I ask my Taiwan friends, he said, 'A little IT terminology.'

**Comment by ghost** [comment]
I didn't do the language translations, please feel free to do a PR to fix what is incorrect.

With the Image Popover, are you asking about integrating the image-attributes plugin into Summernote's Image Modal. This can't be done without extensively modifying Summernote's functionality, that's why it's a separate plugin.

**Comment by yumewang** [comment]
@StudioJunkyard I can not do do a PR.
![11](https://cloud.githubusercontent.com/assets/2267888/20340475/95ba5716-ac1c-11e6-972f-75d79a30d75d.png)

I don't say if it's a separate plugin. I just say there can edit title, alt, class and style attributes at the image popover, but can not edit src attribute. Can you understand me? (Sorry for my poor English.)

**Comment by ghost** [comment]
oh, I get you know, sorry, I was in the middle of thinking about something else. I guess src attribute editing could be handy, I'll have a look at adding it a little later.

Anyone can do PR's, you can edit files using GitHub's pages.

**Comment by yumewang** [comment]
@StudioJunkyard  Thank you. I do a PR. 
'Anyone can do PR's', but not work for me. Maybe I have wrong configure locally. I can pull something, but can not push new branch. I can fixed this problem.
Thank you again.

**Comment by yumewang** [comment]
@StudioJunkyard  I have edited files, and do a PR which did not assign any one to check. If you can not see it, please let me know.

And then, I just can do a PR by fork project. I have closed this test PR.

**Comment by ghost** [comment]
When you do a PR, GitHub will fork it into your account. Then you make changes to the duplicated files in your account. Then you do the PR.

I will then see it, review the changes, then merge it if it's satisfactory.

**Comment by ghost** [comment]
If you don't want the cloned repository in your account you can remove it if you wish.

**Comment by yumewang** [comment]
@StudioJunkyard It works as you said. Thank you.
Best wishes for you.

**Comment by ghost** [comment]
No worries, glad your having fun. :+1:
