### ISSUE TITLE
Translate doesn't work.

### ISSUE THREAD

**Issue by medslt** [StudioJunkyard/summernote-image-attributes#18]
First of all, thank you for this plugin.

I used bower to download this plugin (https://libraries.io/bower/summernote-image-attributes) but translate doesn't work (I think bower doesn't download the last version of plugin)

Thanks for your help !

**Comment by ghost** [comment]
oh ok, I didn't add Bower abilitites to the plugin, so I'm not sure what's going on there.
I'll have a look into, and hopefully learn a little more about Bower.
Sorry, it didn't work for you. Have you tried downloading the plugin and using it from there, just to make sure it works for you with the translation you need?

**Comment by medslt** [comment]
Yes it works fine when I downloaded it from github. Thanks!

**Comment by ghost** [comment]
Cool.

I have no idea what's with Bower. I'm old skool, and prefer to download it and go from there. Must be getting old, maybe I need to look into it, and keep up with the cool kids, lol.
