### ISSUE TITLE
Where to include plugin

### ISSUE THREAD

**Issue by Onikoroshi** [StudioJunkyard/summernote-image-attributes#19]
Sorry to be so dense, but I just couldn't see where to do this.

In the readme (https://github.com/StudioJunkyard/summernote-image-attributes#1-include-js) it says "Include the following code after you include Summernote." Where exactly is that? I have a Rails app that I've inherited, and I "include" Summernote in a few different places (Gemfile, application.js, stylesheets/base.scss). None of those places seem the right spot for the html code the readme presents. Any suggestions would be amazing!

**Comment by Onikoroshi** [comment]
Turns out I just had to put the js file in the file structure such that my current includes (from application.js) caught it. Sorry about the confusion!

**Comment by ghost** [comment]
All good, glad you worked it out.
