### ISSUE TITLE
The value of  "imageDialogLayout" is useless

### ISSUE THREAD

**Issue by v74269v** [StudioJunkyard/summernote-image-attributes#20]
I change the value of  "imageDialogLayout" and nothing change.

![image](https://cloud.githubusercontent.com/assets/25312552/22684669/4d40ad6e-ed58-11e6-8b7c-e9a6016091bd.png)

The value is setted by js.

**Comment by ghost** [comment]
I tried it here, works as expected.
Silly question, after the change did you do a full refresh (`ctrl or shift + f5 or refresh button`), sometimes just refreshing the page, doesn't refresh the script.

**Comment by v74269v** [comment]
JS：
![image](https://cloud.githubusercontent.com/assets/25312552/22719296/b97782dc-eddf-11e6-8a69-99e74cb0cfc4.png)
My code:
![image](https://cloud.githubusercontent.com/assets/25312552/22719380/4e0f7152-ede0-11e6-9912-e691e023c223.png)
My meanning is that the "options.imageDialogLayout" is not the “imageDialogLayout“ I setted  in "imageAttributes".

**Comment by ghost** [comment]
I am understand this correctly, in that when you set the value outside of the plugins options scope they don't get set, but do when outside?

**Comment by v74269v** [comment]
![image](https://cloud.githubusercontent.com/assets/25312552/22725478/9f253194-ee08-11e6-8f43-4b17dcd42898.png)
So it is different with your example. Now I set the value outside like I did.
I just wanna know why did it happen? Is it my mistake?
And thank you for your help.

**Comment by ghost** [comment]
All good, I'm a little confused myself, lol.
I'll have more of a look at this strange thing in a few days, I'm in the middle of building a plugin that checks the accessibility of elements in the editor. And I'm also adding some options to the Find N Replace plugin.
