### ISSUE TITLE
URL field does not accept mailto: links

### ISSUE THREAD

**Issue by unlikenesses** [StudioJunkyard/summernote-image-attributes#25]
My workaround is to remove the conditional at line 562 but it would be better if the regex at line 561 were modified to accept mailto:.

**Comment by ghost** [comment]
Apologies for the amount of time it's taken to respond to this issue.
We may have to also add in the extra HTML5 values into the regex, such as `tel:` as well.

**Comment by DennisSuitters** [comment]
I'm looking into this still, but have discovered a new strange issue, where the link information isn't being read to be displayed in the dialog inputs, however I fixed an issue that wasn't adding links when creating them.

**Comment by DennisSuitters** [comment]
The latest PR fixes this by removing the regex check, at least until I work out a regex that matches all the url types.
