### ISSUE TITLE
Image input send null value

### ISSUE THREAD

**Issue by moiki** [StudioJunkyard/summernote-image-attributes#30]
Hi! I'm using OnImageUpload callback, It works fine when I insert an image. But when I try to replace the image with this plugin, the file input doesn't send a file... it send a null value. 
How can I fix  that ?

**Comment by ghost** [comment]
Have a look at issue #29 I think this may be the same or similar issue.

**Comment by DennisSuitters** [comment]
This is now been fixed with the current PR.
