### ISSUE TITLE
Use on multiple summernote instances on single page

### ISSUE THREAD

**Issue by patricks8** [StudioJunkyard/summernote-image-attributes#41]
Hello,

I like your plugin, but the modal does not work with multiple instances of summernote on a single page because of the id's used for the nav-tabs. Could you add an option so it can work with multiple instances of summernote.

**Comment by DennisSuitters** [comment]
ok, yeah, that is an issue. I am however in the process of adding the plugin as a module to Summernote itself.
I'm pretty sure I use ID attributes to work with the `<label>` attributes for ARIA (Screen Reader compatibility). There would be the same issue when integrated into Summernote. I'm thinking that if the `for` and `id` attributes needed for ARIA are not read out and are only to associate the elements, we may be able to do something like add a timestamp to those attributes if only to seperate them and not have duplicate `id`'s on the same page.

**Comment by DennisSuitters** [comment]
I've just updated stuff to allow different ID's via adding a timestamp when the plugin is initialised. Also added classes for the upcoming updates so formatting works nicely for Summernote Lite.
