### ISSUE TITLE
Image replace through `onImageUpload` improvements needed

### ISSUE THREAD

**Issue by nmandrescu** [StudioJunkyard/summernote-image-attributes#47]
Hello,

When `onImageUpload` callback is setup, there are a couple of issues:

1.  `summernote` sends a list of files (an array) to the `onImageUpload`, while the current library only the file itself. It would be nice to be consistent and send an array here as well. If we want to restrict the replace to the first selection, then we can do:
```
context.triggerEvent('image.upload', [this.files[0]]);
```
2.  When file is uploaded, there is no way to notify the new URL to be used for the image to replace. Please either expose an event or just pass image source to which URL must be updated by the callback:
```
context.triggerEvent('image.upload', [this.files[0]], $imageSrc);
```

P.S. Thanks a lot for such a useful plugin!

**Comment by DennisSuitters** [comment]
Did your PR address the above issues? Sorry, I haven't had the time to do a full review.

**Comment by nmandrescu** [comment]
The PR was for change propagation, this one is different.

I guess best way would be to first get support from the summernote core API, so I created this issue https://github.com/summernote/summernote/issues/2707.
