### ISSUE TITLE
tabs style is not working on bootstrap 4

### ISSUE THREAD

**Issue by digitaldreams** [StudioJunkyard/summernote-image-attributes#48]
Hi 
Thanks for your awesome work. I really appreciate your effort. 
But on thing i notice that tabs style is not working. Can you have a look. 
I am using Bootstrap 4
![tabs style is not working on bootstrap 4](https://user-images.githubusercontent.com/6059541/37599461-fd36358c-2bae-11e8-856b-5efc9d3c6fad.png)

**Comment by DennisSuitters** [comment]
Will have to check that out.

**Comment by JRalph-Hamilton** [comment]
Is there a workaround for this? It still looks the same with bootstrap 4.

**Comment by DennisSuitters** [comment]
The tabs work differently between the different versions of Bootstrap, we may have to separate versions of the plugin, or have an option to set what version of BS is being used so the correct tab layout is used.

**Comment by DennisSuitters** [comment]
I'm waiting on a response from the Summernote Team if we can add a version or settings test like `$.summernote.version;` that can return which of the 3 Summernotes is being used like -bs3, -bs4 or -lite, so then plugins can test which Summernote it's being used with so a programmatic control can be used to display the correct markup for that version, seeing as though Bootstrap use of tabs is different between versions.

**Comment by mobweb** [comment]
As a quick fix for the display issues I made the changes in the attached patch, in case it helps anybody.

[image-attributes-bs4-support.patch.zip](https://github.com/DiemenDesign/summernote-image-attributes/files/3798553/image-attributes-bs4-support.patch.zip)

**Comment by DennisSuitters** [comment]
Turns out it was just a simply missing classes in the markup.
