### ISSUE TITLE
Uglify compilation error

### ISSUE THREAD

**Issue by tlartaud** [StudioJunkyard/summernote-image-attributes#49]
Hi,

Some days ago, I commented this [commit](https://github.com/DiemenDesign/summernote-image-attributes/commit/1f91072e9d93fb351224ae98c8e90e0d1cf9f6ef) which leads to Uglify compilation error.

Any news on this maybe?

Regards.

**Comment by DennisSuitters** [comment]
I just merged a PR from @grandsilence hopefully that fixes your compilation issue and saves us all some time.
