### ISSUE TITLE
Summernote image attributes

### ISSUE THREAD

**Issue by akasham67** [StudioJunkyard/summernote-image-attributes#5]
Hi,

I already integrated this plugin in my application https://github.com/StudioJunkyard/summernote-image-attributes But it's not working perfectly. It shows these errors.

https://drive.google.com/file/d/0BwAzgV3nKU7aTk0xekxlSTZDNFE/view?usp=drivesdk

How can I fix this? Waiting for your reply.

Thank you :)

**Comment by ghost** [comment]
I just had a look using Chrome in Linux Mint, and inspected (or rather looked for) the errors in Chrome Dev Tools, and Firebug. No errors.

What Browser/OS are you using?

Also, I'm using jQuery v2.1

**Comment by ghost** [comment]
First error in your screenshot is jQuery, so your version may not contain the function. The missing function could also be causing the second error to be thrown.

**Comment by akasham67** [comment]
I am using Ubuntu 16.04 LTS as OS and Google Chrome Version 51.0.2704.63 (64-bit). Jquery didn't show this error when I removed summernote-image-attributes.js from my script. I also tried with jQuery v2.1

Here the screenshot:
http://www.awesomescreenshot.com/image/1284371/82006459537d354f922c670dce117145

Thank you :)

**Comment by ghost** [comment]
I'm still not seeing these errors. Are you using the latest Summernote?

Which inspector are you using that's showing the error's?

**Comment by akasham67** [comment]
I already uploaded a sample script. Please if you have time, then download it and check. 
[summernote.zip](https://github.com/StudioJunkyard/summernote-image-attributes/files/287613/summernote.zip)

**Comment by ghost** [comment]
Oh ok, I'd forgotten about this, @MarkosBL was looking into this as his mods were causing this to happen. You can set the options inside the script if you need to, just don't set the options when calling Summernote. I'll have to make a note of this in the readme.
Remove the 

``` javascript
        imageAttributes:{
            icon:'<i class="note-icon-pencil"/>',
            removeEmpty:false // true = remove attributes | false = leave empty if present
        },
        imageShape: {
            icon: '<i class="note-icon-picture"/>'
        }
```

**Comment by akasham67** [comment]
Thank you so much :) Now it's working. Many many thank you for your valuable time.

**Comment by ghost** [comment]
No worries, thank you for bringing this to my attention, I'd forgotten all about it.
