### ISSUE TITLE
Not updating content when using with ngx-summernote

### ISSUE THREAD

**Issue by adeelhussain** [StudioJunkyard/summernote-image-attributes#53]
I am using this plugin, it works but its not triggering `OnChange` event, just Div is updating but not the value!

**Comment by DennisSuitters** [comment]
What is ngx?

**Comment by adeelhussain** [comment]
@DiemenDesign ngx is the wrapper for summernote, allowing us to use with angular 6/7
https://github.com/lula/ngx-summernote

**Comment by DennisSuitters** [comment]
Have you tried using Summernote in it's native form, to make sure the events your expecting to fire do fire?

**Comment by DennisSuitters** [comment]
This issue is over a year old, so I am hoping you were able to fix this, or find a workaround.
