### ISSUE TITLE
summernote not registering change

### ISSUE THREAD

**Issue by bflydesign** [StudioJunkyard/summernote-image-attributes#6]
We are using the vue-html-editor based on summernote. When applying changes in e.g. style, the editor is not registering the change causing vue not to save. Only when adding an extra return or text, we can trigger the change.

To solve this matter we added the next line to the $editBtn.click event, just after the deferred.resolve:

`$note.summernote().trigger('summernote.change');`

Any feedback?

**Comment by ghost** [comment]
Have you checked this behaviour in Summernote itself?

The plugin is meant for the official Summernote, that's cool if you wish to use it in a derivitive.

If you need to add those changes, and those changes work with the official editor, I don't see any reason why the changes can't be added to the plugin, just as long as the changes don't cause issue's. 

There's also no reason why you couldn't fork this to another repo specifically for the editor your using.

**Comment by ghost** [comment]
Hi @bflydesign were you able to work this issue out?

**Comment by bflydesign** [comment]
Hi @StudioJunkyard we added this watch-method to the vue-model which seems working fine to register any change in the editor

```
watch: {
    "model": function (val, oldVal) {
        if (! this.isChanging) {
            this.isChanging = true;
            //  note that setting code value does not automatically trigger
            //  the "summernote.change" event
            var code = (val === null ? "" : val);
            this.control.summernote('code', code);
            this.control.summernote().trigger('summernote.change');
            this.isChanging = false;
        }
    }
}
```

**Comment by ghost** [comment]
Nice, glad you worked something out.
