### ISSUE TITLE
Bootstrap Backdrop breaks page

### ISSUE THREAD

**Issue by aweiand** [StudioJunkyard/summernote-image-attributes#73]
Hi!

I'm having an issue with backdrop. It always shown and I don't now how to get it off....

![image](https://user-images.githubusercontent.com/1443817/149445682-01b22034-296f-46b8-acd8-de4fbca87b8b.png)

**Comment by DennisSuitters** [comment]
Apologies I haven't gotten to this issue sooner. That page you've shown, isn't this plugin (for e.g., there's no lock for the resize options, though I'm interested in adding that).

**Comment by aweiand** [comment]
Hi, no problems ;-)
But, I no longer work with this project, and dont' have more data to you about this...

**Comment by DennisSuitters** [comment]
All good, I'll close this now.
