### ISSUE TITLE
Is not working

### ISSUE THREAD

**Issue by JeroNimoMan** [StudioJunkyard/summernote-image-attributes#74]
here is what i get :

![sum](https://user-images.githubusercontent.com/122772310/212611646-668a78a2-762f-498b-9a04-447f355d3bfa.jpg)

has anyone had the same problem ?

**Comment by JeroNimoMan** [comment]
clicking on tabs does not change anything, all fields supposed to appear remain hidden

**Comment by PENEKhun** [comment]
I found this problem while using bs5.
bs5 uses data-bs-toggle rather than data-toggle for the tab attribute.

So I fixed that part and PR.
