### ISSUE TITLE
can we have a seperate branch for just the imageShape ?

### ISSUE THREAD

**Issue by ctf0** [StudioJunkyard/summernote-image-attributes#9]

**Comment by ghost** [comment]
I don't see why not. They don't need to be together, and with the link attributes it needs to have rel added and role for accesibility.

**Comment by ctf0** [comment]
sweet :dancers:

**Comment by ghost** [comment]
Sorry for the long wait, you can now get the Image Shapes, as seperate plugin.

- [Summernote Image Caption It](https://github.com/StudioJunkyard/summernote-image-captionit)
  - Add Button to Image Popup to add FigCaption and Figure Elements using the TITLE or ALT Text.
- [Summernote Image Shapes](https://github.com/StudioJunkyard/summernote-image-shapes)
  - Add Button to Image Popup to enable selecting Bootstrap Image Shapes.
